config/routes.rb
PersonalPageApp::Application.routes.draw do
  resources :messages
  root  'static_pages#home'
  match '/resume',    to: 'static_pages#resume',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/projects', to: 'static_pages#projects', via: 'get'
  match '/message', to: 'messages#new', via: 'get'

  

end

app/models/message.rb
class Message < ActiveRecord::Base
	before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX }
  validates :msg, presence: true, length: {maximum: 140}
end

app/models/tidbit.rb
class Tidbit < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def show
  	@message = Message.find(params[:id])
  end

  def new
  	@message = Message.new
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def resume
  end

  def about
  end

  def projects
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "James Marquardt"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    All About James Marquardt by James Marquardt
  </small>
  <nav>
    <ul>
      <li><a href="mailto:jamarq@uw.edu">Email Me</a><li>
      <li><a href="http://www.linkedin.com/pub/james-marquardt/65/ba6/226">LinkedIn</a></li>
      <li><a href="http://bbc.com">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "All About James Marquardt", root_path, id: "logo" %>
          <nav>
            <ul class="nav pull-left">
              <li><%= link_to "Resume", resume_path %></li>
              <li><%= link_to "Projects", projects_path %></li>
              <li><%= link_to "About", about_path %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    	
    	<div class="container-fluid">
  			<div class="row-fluid">
    			<div class="span8">
      				<%= yield %>
    			</div>
    			<div class="span4">
     				<%= image_tag("jamesphoto.jpg", :alt => "James Marquardt Smiling") %>
      				<%= image_tag("jamesphoto.jpg", :alt => "James Marquardt Smiling") %> 
   		 		</div>
  			</div>
  			<%= render 'layouts/footer' %>
		</div>
      
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<p>
	<h2>Here's something you might not know about me</h2>
	<% message = Tidbit.order("RANDOM()").first.info %>
	<%= message %>
</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<p>
  This web app is the home for all the public documents, projects, and tutorials by James Marquardt.
</p>

app/views/static_pages/message.html.erb
<% provide(:title, 'Message James') %>
<h1>Send me a message!</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@message) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :msg, "Message" %>
      <%= f.text_field :msg%>

      <%= f.submit "Send", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/static_pages/projects.html.erb
<% provide(:title, 'Projects and Interests') %>
  <h1>NLP is the Thing for Me</h1>
  Currently, my main interest is in the field of natural language processing. <br>
  I became interested in the subject during my sophomore year as an undergrad, <br>
  when the professor of my computer architecture course told the class that he <br>
  hoped none of us were planning on becoming application developers due. His <br>
  claim was that the process of engineering simple software would most likely <br>
  be completely automated within the next ten years, and that even people with <br>
  no technical background would be able to generate most of the software they <br>
  needed.<br>
  Most of the class laughed at the idea, but ever since that moment, I have been <br>
  obsessed with how to make software development as approachable as possible for <br> 
  engineering civilians. <br>
  Seeing as how ordinary people would only be able to express their software needs <br>
  through an unformatted human language, I turned to the study of natural language <br>
  processing.

  <h1>Current Projects / Areas of Study</h1>
  <h2>Algorithm/Specification Alignment Corpus Collection</h2>
  During the Summer of 2013, I constructed a web app to crowdsource the generation <br>
  of Java code based on algorithm descriptions I provided. The goal of this project <br>
  is to build up a corpus of aligned descriptions and algorithms that could later be <br>
  used to devise some sort of translation scheme. The app is currently offline as a <br>
  result of excessive noisy communications. Once I have created a strategy to filter <br>
  noise (i.e. intentionally unusable algorithms), I will redeploy the app and continue <br>
  with collection.<br>
  
  <h2>Machine Language Processing</h2>
  I was recently exposed to the applications of NLP in the field of malware detection. <br>
  Despite the fact that I am by no means a cybersecurity buff, I thought it might be <br>
  worth it to do some reading on the subject. I am currently learning about analogous <br>
  techniques between NLP and MLP (machine language processing).<br>

app/views/static_pages/resume.html.erb
<% provide(:title, 'Resume') %>
<h1>Resume</h1>


    OBJECTIVE: To apply my skills in software and web development technologies and<br>
    techniques on large and impactful projects.

    <h2>EDUCATION</h2>

    <b>Computer Science and Systems, Bachelor of Science</b><br>
    June 14, 2013<br>
    Minor in Mathematics<br>
    University of Washington - Tacoma<br>
    GPA: 3.50<br>

    <b>Computer Science and Systems, Master of Science</b><br>
    Expected 2014

    <h2>PROJECTS</h2>

    <b>Natural Language/Code Text Alignment</b><br>
    2013 - Present<br>
    Created Python based application for gathering text corpora from Stack Exchange.<br>
    Developing Rails application to facilitate crowdsourced corpora generation.<br>

    <b>Database Management Front End Website</b><br>
    2013<br>
    Worked as the lead of a three man team to develop and deploy a MySQL database and<br>
    PHP based dynamic website as a simulation of an agricultural administration page.<br>

    <b>Contest Registration Web Application</b><br>
    2013<br>
    Worked as a member of a team to implement a contest registration system in Java for a<br>
    University of Washington class project. Major contributions included serialized data<br>
    storage, navigation design, and account verification.<br>

    <b>Spreadsheet Application</b><br>
    2012<br>
    Implemented a spreadsheet application with features such as cycle detection,<br>
    summation, and raw type cell input using Java as a class project at the University of<br>
    Washington.<br>
  <h2>EXPERIENCE</h2>
    <b>Mathematics and Computer Science Tutor</b><br>
    Tacoma, WA University of Washington<br>
    2012 – Present<br>
    Instructed university level students on Math and Computer Science topics ranging from<br>
    modeling techniques using differential equations to effective algorithm writing to Java<br>
    fundamentals.

    <b>Infantry Sergeant</b><br>
    US Army; Joint Base Lewis-McChord, WA<br>
    2004 – 2010

    <h2>SKILLS</h2>
    •Native application development with Java, C, Python<br>
    •Web app development using Rails, HTML/(Sa)CSS, SaCSS, PHP, Java/CoffeeScript<br>
    •Relational Database development and administration (MySQL, PostgreSQL, SQLite)<br>
    •Effective use of testing tools such as RSpec and JUnit in Test Driven Development<br>